# Generated by Django 4.2.5 on 2023-09-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=123, upload_to='MOVIE MEDIA '),
            preserve_default=False,
        ),
    ]
