# Generated by Django 4.2.5 on 2023-09-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(upload_to='MOVIEMEDIA'),
        ),
    ]
